### ISSUE TITLE
Auth0.OidcClient.UWP v3.1.0 is broken

### ISSUE THREAD

**Issue by under3415** [auth0-community/auth0-uwp-oidc-samples#13]
# Issue Report

If you are reporting a bug, please fill the sections below (if they are applicable), otherwise feel free to delete those that don't apply. Thank you! 🙏🏼

### Description

"Forbidden" error when trying to display login screen in UWP sample app

### Expected behaviour

Login screen to be displayed

### Actual behaviour 

The screen does not show and forbidden error is returned

### Steps to reproduce the problem

Download sample app, update to Auth0.OidcClient.UWP v3.1.0, run it. 
Note that populating the app ms-app uri causes the login screen to display, but it does not return to the app afterwards. When I downgraded to version 2.4.3 returnUri is pre-populated and everything works as expected. 

### Language / Framework Versions

1. **Language used:** C#
2. **Framework used:** Microsoft.NETCore.UniversalWindowsPlatform v6.2.9

### Testing environment

1. **Operating system:** Win10 
2. **Browser version:** N/A

### Screenshots

Feel free to insert here any screenshots that you consider helpful in solving your issue.

**Filling this, you're helping yourself and repo maintainers in solving your issues quicker! Teamwork makes the dreamwork 🤜🏼🤛🏻**

**Comment by lukenuttall** [comment]
I got this to work adding `https://{Domain}/mobile` to the callback and logout URIs

**Comment by damieng** [comment]
I believe this is fixed now with the latest changes, if this issue still persists respond to this issue and we'll reopen it.

**Comment by marshallcoco** [comment]
Hi
I'm getting a similar issue right now Auth0.OidcClient.UWP v3.1.2
To not get the "Forbidden" answer, I include my App callback URI (ms-app://...) as RedirectUri and PostLogoutRedirectUri.
When doing this, I have a succesful login message in Auth0 logs.
However, instead of going back to my app and retrieving the succesful connection data, I reach a "you'll need a new app..." page from which I can't do anything except cancelling - then I go back to my application with a "UserCancel" error.

**Comment by luisve1427** [comment]
> Hi
> I'm getting a similar issue right now Auth0.OidcClient.UWP v3.1.2
> To not get the "Forbidden" answer, I include my App callback URI (ms-app://...) as RedirectUri and PostLogoutRedirectUri.
> When doing this, I have a succesful login message in Auth0 logs.
> However, instead of going back to my app and retrieving the succesful connection data, I reach a "you'll need a new app..." page from which I can't do anything except cancelling - then I go back to my application with a "UserCancel" error.

Any luck on fixing this? I am having the same issue

**Comment by frederikprijck** [comment]
Sorry for the delayed reply. My guess it this is due to a misconfiguration on the Callback URL in Auth0. Apparantly our quickstart was not updated to align with `Auth0.OidcClient.UWP v3.1.2`.

Could you try and use the following callback URL in your Auth0 dashboard: `https://{AUTH0_DOMAIN}/mobile` (replace {AUTH0_DOMAIN} with your tenant's domain).

Another solution that might work is setting the Browser to `new WebAuthenticationBrokerBrowser()`, in that case you also need to provide the `RedirectUri`:

```
client = new Auth0Client(new Auth0ClientOptions
{
    Domain = domain,
    ClientId = clientId,
    Browser = new WebAuthenticationBrokerBrowser(),
    RedirectUri = Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri().AbsoluteUri
});
```

Let me know if that does or does not help.

**Comment by frederikprijck** [comment]
The quickstart has been updated.
